# fly.toml app configuration file generated for spotify-re-discoverer on 2023-06-20T20:28:28-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "spotify-re-discoverer"
primary_region = "yyz"
kill_signal = "SIGTERM"
kill_timeout = "5s"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "spotify-re-discoverer.fly.dev"
  PHX_SERVER = "true"
  PORT = "8080"
  PRIMARY_REGION = "yyz"
