import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :spotify_re_discoverer, SpotifyReDiscovererWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

config :spotify_re_discoverer, :spotify,
  redirect_uri: "https://spotify-re-discoverer.fly.dev/spotify/callback"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: SpotifyReDiscoverer.Finch

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
